-- Create "users" table
CREATE TABLE "public"."users" (
  "id" uuid NOT NULL,
  "kratos_id" uuid NOT NULL,
  "name" text NOT NULL,
  "highlighted_photo_id" bigint NULL DEFAULT 0,
  "locale" character varying(10) NULL DEFAULT 'ja',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "description" text NULL,
  "locality" text NULL,
  "administrative_area" text NULL,
  "country_code" character(2) NULL DEFAULT 'JP',
  "postal_code" character varying(20) NULL,
  "geom" public.geometry(Point,4326) NULL,
  "first_name" text NULL,
  "last_name" text NULL,
  "email" text NULL,
  "has_set_location" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_email_key" UNIQUE ("email"),
  CONSTRAINT "users_kratos_id_key" UNIQUE ("kratos_id")
);
-- Create "routes" table
CREATE TABLE "public"."routes" (
  "id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL,
  "description" text NOT NULL DEFAULT '',
  "highlighted_photo_id" bigint NULL DEFAULT 0,
  "has_course_points" boolean NOT NULL DEFAULT false,
  "distance" double precision NOT NULL,
  "duration" integer NOT NULL,
  "elevation_gain" double precision NOT NULL DEFAULT 0,
  "elevation_loss" double precision NOT NULL DEFAULT 0,
  "path_geom" public.geometry(LineString,4326) NOT NULL,
  "bbox" public.geometry(Polygon,4326) NOT NULL GENERATED ALWAYS AS (public.st_envelope(path_geom)) STORED,
  "first_point" public.geometry(Point,4326) NOT NULL GENERATED ALWAYS AS (public.st_startpoint(path_geom)) STORED,
  "last_point" public.geometry(Point,4326) NOT NULL GENERATED ALWAYS AS (public.st_endpoint(path_geom)) STORED,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deleted_at" timestamptz NULL,
  "visibility" smallint NOT NULL DEFAULT 1,
  PRIMARY KEY ("id"),
  CONSTRAINT "routes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "routes_distance_check" CHECK (distance >= (0)::double precision),
  CONSTRAINT "routes_duration_check" CHECK (duration >= 0),
  CONSTRAINT "routes_elevation_gain_check" CHECK (elevation_gain >= (0)::double precision),
  CONSTRAINT "routes_elevation_loss_check" CHECK (elevation_loss >= (0)::double precision),
  CONSTRAINT "routes_path_geom_check" CHECK (NOT public.st_isempty(path_geom)),
  CONSTRAINT "routes_path_geom_check1" CHECK (public.st_npoints(path_geom) >= 2),
  CONSTRAINT "routes_visibility_check" CHECK (visibility = ANY (ARRAY[0, 1, 2]))
);
-- Create "course_point" table
CREATE TABLE "public"."course_point" (
  "id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "step_order" integer NOT NULL,
  "seg_dist_m" double precision NULL,
  "cum_dist_m" double precision NULL,
  "duration" double precision NULL,
  "instruction" text NULL,
  "road_name" text NULL,
  "maneuver_type" text NULL,
  "modifier" text NULL,
  "location" public.geometry(Point,4326) NULL,
  "bearing_before" integer NULL,
  "bearing_after" integer NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "course_point_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "route_comments" table
CREATE TABLE "public"."route_comments" (
  "id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "parent_id" uuid NULL,
  "content" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "comments_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."route_comments" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "route_comments_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "route_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "route_images" table
CREATE TABLE "public"."route_images" (
  "id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "s3_key" text NOT NULL,
  "width" integer NULL,
  "height" integer NULL,
  "size" bigint NULL,
  "type" text NOT NULL,
  "visibility" smallint NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "route_images_s3_key_key" UNIQUE ("s3_key"),
  CONSTRAINT "route_images_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "route_images_visibility_check" CHECK (visibility = ANY (ARRAY[0, 1, 2]))
);
-- Create "route_likes" table
CREATE TABLE "public"."route_likes" (
  "id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "route_likes_user_id_route_id_key" UNIQUE ("user_id", "route_id"),
  CONSTRAINT "route_likes_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "route_likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "route_saves" table
CREATE TABLE "public"."route_saves" (
  "id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "route_id" uuid NOT NULL,
  "pinned" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "route_saves_user_id_route_id_key" UNIQUE ("user_id", "route_id"),
  CONSTRAINT "route_saves_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "public"."routes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "route_saves_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE
);
-- Create "trips" table
CREATE TABLE "public"."trips" (
  "id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "name" text NOT NULL DEFAULT '',
  "description" text NOT NULL DEFAULT '',
  "visibility" smallint NOT NULL DEFAULT 0,
  "highlighted_photo_id" bigint NOT NULL DEFAULT 0,
  "path_geom" public.geometry(LineString,4326) NULL,
  "first_point" public.geometry(Point,4326) NULL,
  "last_point" public.geometry(Point,4326) NULL,
  "bbox_geom" public.geometry(Polygon,4326) NULL,
  "distance" double precision NULL,
  "duration" integer NULL,
  "moving_time" integer NULL,
  "elevation_gain" double precision NULL,
  "elevation_loss" double precision NULL,
  "avg_speed" double precision NULL,
  "max_speed" double precision NULL,
  "avg_cad" double precision NULL,
  "max_cad" double precision NULL,
  "min_cad" double precision NULL,
  "max_hr" integer NULL,
  "min_hr" integer NULL,
  "avg_watts" double precision NULL,
  "max_watts" double precision NULL,
  "min_watts" double precision NULL,
  "avg_watts_estimated" boolean NULL,
  "avg_power_estimated" double precision NULL,
  "calories" double precision NULL,
  "is_gps" boolean NOT NULL DEFAULT false,
  "is_stationary" boolean NOT NULL DEFAULT false,
  "processed" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "deleted_at" timestamptz NULL,
  "departed_at" timestamptz NULL,
  "time_zone" text NULL,
  "utc_offset" integer NULL,
  "activity_type_id" integer NOT NULL DEFAULT 0,
  "pace" double precision NULL,
  "moving_pace" double precision NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "trips_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "trips_avg_speed_check" CHECK ((avg_speed IS NULL) OR (avg_speed >= (0)::double precision)),
  CONSTRAINT "trips_distance_check" CHECK ((distance IS NULL) OR (distance >= (0)::double precision)),
  CONSTRAINT "trips_duration_check" CHECK ((duration IS NULL) OR (duration >= 0)),
  CONSTRAINT "trips_elevation_gain_check" CHECK ((elevation_gain IS NULL) OR (elevation_gain >= (0)::double precision)),
  CONSTRAINT "trips_elevation_loss_check" CHECK ((elevation_loss IS NULL) OR (elevation_loss >= (0)::double precision)),
  CONSTRAINT "trips_max_speed_check" CHECK ((max_speed IS NULL) OR (max_speed >= (0)::double precision)),
  CONSTRAINT "trips_moving_time_check" CHECK ((moving_time IS NULL) OR (moving_time >= 0)),
  CONSTRAINT "trips_visibility_check" CHECK (visibility = ANY (ARRAY[0, 1, 2]))
);
-- Create "trip_images" table
CREATE TABLE "public"."trip_images" (
  "id" uuid NOT NULL,
  "trip_id" uuid NOT NULL,
  "s3_key" text NOT NULL,
  "width" integer NULL,
  "height" integer NULL,
  "size" bigint NULL,
  "type" text NOT NULL,
  "visibility" smallint NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "trip_images_s3_key_key" UNIQUE ("s3_key"),
  CONSTRAINT "trip_images_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "public"."trips" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "trip_images_visibility_check" CHECK (visibility = ANY (ARRAY[0, 1, 2]))
);
