// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type CoursePoint struct {
	ID            int64        `json:"id"`
	Ulid          string       `json:"ulid"`
	RouteID       *int64       `json:"route_id"`
	StepOrder     int32        `json:"step_order"`
	SegDistM      *float64     `json:"seg_dist_m"`
	CumDistM      *float64     `json:"cum_dist_m"`
	Duration      *float64     `json:"duration"`
	Instruction   *string      `json:"instruction"`
	RoadName      *string      `json:"road_name"`
	ManeuverType  *string      `json:"maneuver_type"`
	Modifier      *string      `json:"modifier"`
	Location      *OrbGeometry `json:"location"`
	BearingBefore *int32       `json:"bearing_before"`
	BearingAfter  *int32       `json:"bearing_after"`
}

type Route struct {
	ID                 int64       `json:"id"`
	Ulid               string      `json:"ulid"`
	UserID             int64       `json:"user_id"`
	Name               string      `json:"name"`
	Description        string      `json:"description"`
	HighlightedPhotoID *int64      `json:"highlighted_photo_id"`
	HasCoursePoints    bool        `json:"has_course_points"`
	Distance           float64     `json:"distance"`
	Duration           int32       `json:"duration"`
	ElevationGain      float64     `json:"elevation_gain"`
	ElevationLoss      float64     `json:"elevation_loss"`
	PathGeom           OrbGeometry `json:"path_geom"`
	Bbox               OrbGeometry `json:"bbox"`
	FirstPoint         OrbGeometry `json:"first_point"`
	LastPoint          OrbGeometry `json:"last_point"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	DeletedAt          *time.Time  `json:"deleted_at"`
	Visibility         int16       `json:"visibility"`
}

type RouteComment struct {
	ID        int64      `json:"id"`
	Ulid      string     `json:"ulid"`
	UserID    int64      `json:"user_id"`
	RouteID   int64      `json:"route_id"`
	ParentID  *int64     `json:"parent_id"`
	Content   string     `json:"content"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type RouteImage struct {
	ID         int64     `json:"id"`
	Ulid       string    `json:"ulid"`
	RouteID    int64     `json:"route_id"`
	S3Key      string    `json:"s3_key"`
	Width      *int32    `json:"width"`
	Height     *int32    `json:"height"`
	Size       *int64    `json:"size"`
	Type       string    `json:"type"`
	Visibility int16     `json:"visibility"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RouteLike struct {
	ID        int64     `json:"id"`
	Ulid      string    `json:"ulid"`
	UserID    int64     `json:"user_id"`
	RouteID   int64     `json:"route_id"`
	CreatedAt time.Time `json:"created_at"`
}

type RouteSafe struct {
	ID        int64      `json:"id"`
	Ulid      string     `json:"ulid"`
	UserID    int64      `json:"user_id"`
	RouteID   int64      `json:"route_id"`
	Pinned    bool       `json:"pinned"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Trip struct {
	ID                 int64        `json:"id"`
	Ulid               string       `json:"ulid"`
	UserID             int64        `json:"user_id"`
	Name               string       `json:"name"`
	Description        string       `json:"description"`
	Visibility         int16        `json:"visibility"`
	HighlightedPhotoID int64        `json:"highlighted_photo_id"`
	PathGeom           *OrbGeometry `json:"path_geom"`
	FirstPoint         *OrbGeometry `json:"first_point"`
	LastPoint          *OrbGeometry `json:"last_point"`
	BboxGeom           *OrbGeometry `json:"bbox_geom"`
	Distance           *float64     `json:"distance"`
	Duration           *int32       `json:"duration"`
	MovingTime         *int32       `json:"moving_time"`
	ElevationGain      *float64     `json:"elevation_gain"`
	ElevationLoss      *float64     `json:"elevation_loss"`
	AvgSpeed           *float64     `json:"avg_speed"`
	MaxSpeed           *float64     `json:"max_speed"`
	AvgCad             *float64     `json:"avg_cad"`
	MaxCad             *float64     `json:"max_cad"`
	MinCad             *float64     `json:"min_cad"`
	MaxHr              *int32       `json:"max_hr"`
	MinHr              *int32       `json:"min_hr"`
	AvgWatts           *float64     `json:"avg_watts"`
	MaxWatts           *float64     `json:"max_watts"`
	MinWatts           *float64     `json:"min_watts"`
	AvgWattsEstimated  *bool        `json:"avg_watts_estimated"`
	AvgPowerEstimated  *float64     `json:"avg_power_estimated"`
	Calories           *float64     `json:"calories"`
	IsGps              bool         `json:"is_gps"`
	IsStationary       bool         `json:"is_stationary"`
	Processed          bool         `json:"processed"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	DeletedAt          *time.Time   `json:"deleted_at"`
	DepartedAt         *time.Time   `json:"departed_at"`
	TimeZone           *string      `json:"time_zone"`
	UtcOffset          *int32       `json:"utc_offset"`
	ActivityTypeID     int32        `json:"activity_type_id"`
	Pace               *float64     `json:"pace"`
	MovingPace         *float64     `json:"moving_pace"`
}

type TripImage struct {
	ID         int64     `json:"id"`
	Ulid       string    `json:"ulid"`
	TripID     int64     `json:"trip_id"`
	S3Key      string    `json:"s3_key"`
	Width      *int32    `json:"width"`
	Height     *int32    `json:"height"`
	Size       *int64    `json:"size"`
	Type       string    `json:"type"`
	Visibility int16     `json:"visibility"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID                 int64        `json:"id"`
	Ulid               string       `json:"ulid"`
	Name               string       `json:"name"`
	HighlightedPhotoID *int64       `json:"highlighted_photo_id"`
	Locale             *string      `json:"locale"`
	CreatedAt          time.Time    `json:"created_at"`
	UpdatedAt          time.Time    `json:"updated_at"`
	Description        *string      `json:"description"`
	Locality           *string      `json:"locality"`
	AdministrativeArea *string      `json:"administrative_area"`
	CountryCode        *string      `json:"country_code"`
	PostalCode         *string      `json:"postal_code"`
	Geom               *OrbGeometry `json:"geom"`
	FirstName          *string      `json:"first_name"`
	LastName           *string      `json:"last_name"`
	Email              *string      `json:"email"`
	HasSetLocation     bool         `json:"has_set_location"`
}
