// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoursePoint struct {
	ID            int64         `json:"id"`
	RouteID       pgtype.Int8   `json:"route_id"`
	StepOrder     int32         `json:"step_order"`
	SegDistM      pgtype.Float8 `json:"seg_dist_m"`
	CumDistM      pgtype.Float8 `json:"cum_dist_m"`
	Duration      pgtype.Float8 `json:"duration"`
	Instruction   pgtype.Text   `json:"instruction"`
	RoadName      pgtype.Text   `json:"road_name"`
	ManeuverType  pgtype.Text   `json:"maneuver_type"`
	Modifier      pgtype.Text   `json:"modifier"`
	Location      *OrbGeometry  `json:"location"`
	BearingBefore pgtype.Int4   `json:"bearing_before"`
	BearingAfter  pgtype.Int4   `json:"bearing_after"`
}

type Route struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	HighlightedPhotoID pgtype.Int8        `json:"highlighted_photo_id"`
	HasCoursePoints    bool               `json:"has_course_points"`
	Distance           float64            `json:"distance"`
	Duration           pgtype.Int4        `json:"duration"`
	ElevationGain      float64            `json:"elevation_gain"`
	ElevationLoss      float64            `json:"elevation_loss"`
	PathGeom           OrbGeometry        `json:"path_geom"`
	Bbox               OrbGeometry        `json:"bbox"`
	FirstPoint         OrbGeometry        `json:"first_point"`
	LastPoint          OrbGeometry        `json:"last_point"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	Visibility         int16              `json:"visibility"`
}

type RouteComment struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	RouteID   int64              `json:"route_id"`
	ParentID  pgtype.Int8        `json:"parent_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RouteImage struct {
	ID         int64              `json:"id"`
	RouteID    int64              `json:"route_id"`
	S3Key      string             `json:"s3_key"`
	Width      pgtype.Int4        `json:"width"`
	Height     pgtype.Int4        `json:"height"`
	Size       pgtype.Int8        `json:"size"`
	Type       string             `json:"type"`
	Visibility int16              `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RouteLike struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	RouteID   int64              `json:"route_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RouteSafe struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	RouteID   int64              `json:"route_id"`
	Pinned    bool               `json:"pinned"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Trip struct {
	ID                 int64              `json:"id"`
	UserID             int64              `json:"user_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	Visibility         int16              `json:"visibility"`
	HighlightedPhotoID int64              `json:"highlighted_photo_id"`
	PathGeom           *OrbGeometry       `json:"path_geom"`
	FirstPoint         *OrbGeometry       `json:"first_point"`
	LastPoint          *OrbGeometry       `json:"last_point"`
	BboxGeom           *OrbGeometry       `json:"bbox_geom"`
	Distance           pgtype.Float8      `json:"distance"`
	Duration           pgtype.Int4        `json:"duration"`
	MovingTime         pgtype.Int4        `json:"moving_time"`
	ElevationGain      pgtype.Float8      `json:"elevation_gain"`
	ElevationLoss      pgtype.Float8      `json:"elevation_loss"`
	AvgSpeed           pgtype.Float8      `json:"avg_speed"`
	MaxSpeed           pgtype.Float8      `json:"max_speed"`
	AvgCad             pgtype.Float8      `json:"avg_cad"`
	MaxCad             pgtype.Float8      `json:"max_cad"`
	MinCad             pgtype.Float8      `json:"min_cad"`
	MaxHr              pgtype.Int4        `json:"max_hr"`
	MinHr              pgtype.Int4        `json:"min_hr"`
	AvgWatts           pgtype.Float8      `json:"avg_watts"`
	MaxWatts           pgtype.Float8      `json:"max_watts"`
	MinWatts           pgtype.Float8      `json:"min_watts"`
	AvgWattsEstimated  pgtype.Bool        `json:"avg_watts_estimated"`
	AvgPowerEstimated  pgtype.Float8      `json:"avg_power_estimated"`
	Calories           pgtype.Float8      `json:"calories"`
	IsGps              bool               `json:"is_gps"`
	IsStationary       bool               `json:"is_stationary"`
	Processed          bool               `json:"processed"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	DepartedAt         pgtype.Timestamptz `json:"departed_at"`
	TimeZone           pgtype.Text        `json:"time_zone"`
	UtcOffset          pgtype.Int4        `json:"utc_offset"`
	ActivityTypeID     int32              `json:"activity_type_id"`
	Pace               pgtype.Float8      `json:"pace"`
	MovingPace         pgtype.Float8      `json:"moving_pace"`
}

type TripImage struct {
	ID         int64              `json:"id"`
	TripID     int64              `json:"trip_id"`
	S3Key      string             `json:"s3_key"`
	Width      pgtype.Int4        `json:"width"`
	Height     pgtype.Int4        `json:"height"`
	Size       pgtype.Int8        `json:"size"`
	Type       string             `json:"type"`
	Visibility int16              `json:"visibility"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                 int64              `json:"id"`
	Name               string             `json:"name"`
	HighlightedPhotoID pgtype.Int8        `json:"highlighted_photo_id"`
	Locale             pgtype.Text        `json:"locale"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Description        pgtype.Text        `json:"description"`
	Locality           pgtype.Text        `json:"locality"`
	AdministrativeArea pgtype.Text        `json:"administrative_area"`
	CountryCode        pgtype.Text        `json:"country_code"`
	PostalCode         pgtype.Text        `json:"postal_code"`
	Geom               *OrbGeometry       `json:"geom"`
	FirstName          pgtype.Text        `json:"first_name"`
	LastName           pgtype.Text        `json:"last_name"`
	Email              pgtype.Text        `json:"email"`
	HasSetLocation     pgtype.Bool        `json:"has_set_location"`
}
