// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    name, email, total_trip_distance, total_trip_duration, total_trip_elevation_gain, geom, first_name, last_name, has_set_location
) VALUES (
    $1, $2, $3, $4, $5, ST_SetSRID(ST_MakePoint($6, $7), 4326), $8, $9, $10
) RETURNING id, name, highlighted_photo_id, locale, created_at, description, locality, administrative_area, country_code, postal_code, total_trip_distance, total_trip_duration, total_trip_elevation_gain, geom, first_name, last_name, email, has_set_location
`

type CreateUserParams struct {
	Name                   string        `json:"name"`
	Email                  pgtype.Text   `json:"email"`
	TotalTripDistance      pgtype.Float8 `json:"total_trip_distance"`
	TotalTripDuration      pgtype.Float8 `json:"total_trip_duration"`
	TotalTripElevationGain pgtype.Float8 `json:"total_trip_elevation_gain"`
	StMakepoint            interface{}   `json:"st_makepoint"`
	StMakepoint_2          interface{}   `json:"st_makepoint_2"`
	FirstName              pgtype.Text   `json:"first_name"`
	LastName               pgtype.Text   `json:"last_name"`
	HasSetLocation         pgtype.Bool   `json:"has_set_location"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.TotalTripDistance,
		arg.TotalTripDuration,
		arg.TotalTripElevationGain,
		arg.StMakepoint,
		arg.StMakepoint_2,
		arg.FirstName,
		arg.LastName,
		arg.HasSetLocation,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HighlightedPhotoID,
		&i.Locale,
		&i.CreatedAt,
		&i.Description,
		&i.Locality,
		&i.AdministrativeArea,
		&i.CountryCode,
		&i.PostalCode,
		&i.TotalTripDistance,
		&i.TotalTripDuration,
		&i.TotalTripElevationGain,
		&i.Geom,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HasSetLocation,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, highlighted_photo_id, locale, created_at, description, locality, administrative_area, country_code, postal_code, total_trip_distance, total_trip_duration, total_trip_elevation_gain, geom, first_name, last_name, email, has_set_location FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HighlightedPhotoID,
		&i.Locale,
		&i.CreatedAt,
		&i.Description,
		&i.Locality,
		&i.AdministrativeArea,
		&i.CountryCode,
		&i.PostalCode,
		&i.TotalTripDistance,
		&i.TotalTripDuration,
		&i.TotalTripElevationGain,
		&i.Geom,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.HasSetLocation,
	)
	return i, err
}
