// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/route/route_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/route/route_repository.go -destination=internal/domain/route/mock_route_repository.go -package route
//

// Package route is a generated GoMock package.
package route

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRouteRepository is a mock of IRouteRepository interface.
type MockIRouteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRouteRepositoryMockRecorder
	isgomock struct{}
}

// MockIRouteRepositoryMockRecorder is the mock recorder for MockIRouteRepository.
type MockIRouteRepositoryMockRecorder struct {
	mock *MockIRouteRepository
}

// NewMockIRouteRepository creates a new mock instance.
func NewMockIRouteRepository(ctrl *gomock.Controller) *MockIRouteRepository {
	mock := &MockIRouteRepository{ctrl: ctrl}
	mock.recorder = &MockIRouteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRouteRepository) EXPECT() *MockIRouteRepositoryMockRecorder {
	return m.recorder
}

// CountRoutesByUserID mocks base method.
func (m *MockIRouteRepository) CountRoutesByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRoutesByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRoutesByUserID indicates an expected call of CountRoutesByUserID.
func (mr *MockIRouteRepositoryMockRecorder) CountRoutesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRoutesByUserID", reflect.TypeOf((*MockIRouteRepository)(nil).CountRoutesByUserID), ctx, userID)
}

// DeleteRoute mocks base method.
func (m *MockIRouteRepository) DeleteRoute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoute indicates an expected call of DeleteRoute.
func (mr *MockIRouteRepositoryMockRecorder) DeleteRoute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoute", reflect.TypeOf((*MockIRouteRepository)(nil).DeleteRoute), ctx, id)
}

// GetRouteByID mocks base method.
func (m *MockIRouteRepository) GetRouteByID(ctx context.Context, id string) (*Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouteByID", ctx, id)
	ret0, _ := ret[0].(*Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRouteByID indicates an expected call of GetRouteByID.
func (mr *MockIRouteRepositoryMockRecorder) GetRouteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouteByID", reflect.TypeOf((*MockIRouteRepository)(nil).GetRouteByID), ctx, id)
}

// GetRoutesByUserID mocks base method.
func (m *MockIRouteRepository) GetRoutesByUserID(ctx context.Context, userID string) ([]*Route, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoutesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*Route)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoutesByUserID indicates an expected call of GetRoutesByUserID.
func (mr *MockIRouteRepositoryMockRecorder) GetRoutesByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoutesByUserID", reflect.TypeOf((*MockIRouteRepository)(nil).GetRoutesByUserID), ctx, userID)
}

// SaveRoute mocks base method.
func (m *MockIRouteRepository) SaveRoute(ctx context.Context, route *Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRoute", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRoute indicates an expected call of SaveRoute.
func (mr *MockIRouteRepositoryMockRecorder) SaveRoute(ctx, route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRoute", reflect.TypeOf((*MockIRouteRepository)(nil).SaveRoute), ctx, route)
}

// UpdateRoute mocks base method.
func (m *MockIRouteRepository) UpdateRoute(ctx context.Context, route *Route) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoute", ctx, route)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoute indicates an expected call of UpdateRoute.
func (mr *MockIRouteRepositoryMockRecorder) UpdateRoute(ctx, route any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoute", reflect.TypeOf((*MockIRouteRepository)(nil).UpdateRoute), ctx, route)
}
