// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/trip/trip_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/trip/trip_repository.go -destination=internal/domain/trip/mock_trip_repository.go -package trip
//

// Package trip is a generated GoMock package.
package trip

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITripRepository is a mock of ITripRepository interface.
type MockITripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITripRepositoryMockRecorder
	isgomock struct{}
}

// MockITripRepositoryMockRecorder is the mock recorder for MockITripRepository.
type MockITripRepositoryMockRecorder struct {
	mock *MockITripRepository
}

// NewMockITripRepository creates a new mock instance.
func NewMockITripRepository(ctrl *gomock.Controller) *MockITripRepository {
	mock := &MockITripRepository{ctrl: ctrl}
	mock.recorder = &MockITripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITripRepository) EXPECT() *MockITripRepositoryMockRecorder {
	return m.recorder
}

// CountTripsByUserID mocks base method.
func (m *MockITripRepository) CountTripsByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTripsByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTripsByUserID indicates an expected call of CountTripsByUserID.
func (mr *MockITripRepositoryMockRecorder) CountTripsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTripsByUserID", reflect.TypeOf((*MockITripRepository)(nil).CountTripsByUserID), ctx, userID)
}

// DeleteTrip mocks base method.
func (m *MockITripRepository) DeleteTrip(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrip", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrip indicates an expected call of DeleteTrip.
func (mr *MockITripRepositoryMockRecorder) DeleteTrip(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrip", reflect.TypeOf((*MockITripRepository)(nil).DeleteTrip), ctx, id)
}

// GetTripByID mocks base method.
func (m *MockITripRepository) GetTripByID(ctx context.Context, id string) (*Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripByID", ctx, id)
	ret0, _ := ret[0].(*Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripByID indicates an expected call of GetTripByID.
func (mr *MockITripRepositoryMockRecorder) GetTripByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripByID", reflect.TypeOf((*MockITripRepository)(nil).GetTripByID), ctx, id)
}

// GetTripByKratosID mocks base method.
func (m *MockITripRepository) GetTripByKratosID(ctx context.Context, kratosID string) ([]*Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripByKratosID", ctx, kratosID)
	ret0, _ := ret[0].([]*Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripByKratosID indicates an expected call of GetTripByKratosID.
func (mr *MockITripRepositoryMockRecorder) GetTripByKratosID(ctx, kratosID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripByKratosID", reflect.TypeOf((*MockITripRepository)(nil).GetTripByKratosID), ctx, kratosID)
}

// GetTripsByUserID mocks base method.
func (m *MockITripRepository) GetTripsByUserID(ctx context.Context, userID string) ([]*Trip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTripsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*Trip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTripsByUserID indicates an expected call of GetTripsByUserID.
func (mr *MockITripRepositoryMockRecorder) GetTripsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTripsByUserID", reflect.TypeOf((*MockITripRepository)(nil).GetTripsByUserID), ctx, userID)
}

// SaveTrip mocks base method.
func (m *MockITripRepository) SaveTrip(ctx context.Context, trip *Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTrip", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTrip indicates an expected call of SaveTrip.
func (mr *MockITripRepositoryMockRecorder) SaveTrip(ctx, trip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTrip", reflect.TypeOf((*MockITripRepository)(nil).SaveTrip), ctx, trip)
}

// UpdateTrip mocks base method.
func (m *MockITripRepository) UpdateTrip(ctx context.Context, trip *Trip) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrip", ctx, trip)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrip indicates an expected call of UpdateTrip.
func (mr *MockITripRepositoryMockRecorder) UpdateTrip(ctx, trip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrip", reflect.TypeOf((*MockITripRepository)(nil).UpdateTrip), ctx, trip)
}
